### K-Nearest Neighbors (KNN) - Classification & Regression


In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

## Austin dataset

In [20]:
# Load Austin dataset
austin_df = pd.read_csv("/Users/sohanaziz/Documents/AI for leaders sem 2/Datasets/cleaned datasets/week 2/cleaned_austin_data.csv")

# Create binary classification target
median_price = austin_df['latestPrice'].median()
austin_df['high_price'] = (austin_df['latestPrice'] > median_price).astype(int)

# ----------- Classification -----------
# Drop irrelevant/non-numeric columns
df_class = austin_df.drop(columns=['city', 'latest_saledate']).dropna()
df_class = df_class.select_dtypes(include=[np.number])

X = df_class.drop(columns=['high_price'])
y = df_class['high_price']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Run KNN Classification with all distance metrics
for metric in ['euclidean', 'manhattan', 'minkowski']:
    print(f"\n--- Austin KNN Classification ({metric}) ---")
    knn_clf = KNeighborsClassifier(n_neighbors=5, metric=metric)
    knn_clf.fit(X_train_cls, y_train_cls)
    y_pred_cls = knn_clf.predict(X_test_cls)
    print("Accuracy:", accuracy_score(y_test_cls, y_pred_cls))
    print("Confusion Matrix:\n", confusion_matrix(y_test_cls, y_pred_cls))
    print("Classification Report:\n", classification_report(y_test_cls, y_pred_cls))

# ----------- Regression -----------
# Drop classification target + non-numeric columns
df_reg = austin_df.drop(columns=['high_price', 'city', 'latest_saledate']).dropna()
df_reg = df_reg.select_dtypes(include=[np.number])

X = df_reg.drop(columns=['latestPrice'])
y = df_reg['latestPrice']

X_scaled = scaler.fit_transform(X)
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Run KNN Regression with all distance metrics
for metric in ['euclidean', 'manhattan', 'minkowski']:
    print(f"\n--- Austin KNN Regression ({metric}) ---")
    knn_reg = KNeighborsRegressor(n_neighbors=5, metric=metric)
    knn_reg.fit(X_train_reg, y_train_reg)
    y_pred_reg = knn_reg.predict(X_test_reg)
    rmse = np.sqrt(mean_squared_error(y_test_reg, y_pred_reg))
    r2 = r2_score(y_test_reg, y_pred_reg)
    print(f"RMSE: {rmse:.2f}, R²: {r2:.4f}")


--- Austin KNN Classification (euclidean) ---
Accuracy: 0.8369028006589786
Confusion Matrix:
 [[1335  199]
 [ 296 1205]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.87      0.84      1534
           1       0.86      0.80      0.83      1501

    accuracy                           0.84      3035
   macro avg       0.84      0.84      0.84      3035
weighted avg       0.84      0.84      0.84      3035


--- Austin KNN Classification (manhattan) ---
Accuracy: 0.8543657331136738
Confusion Matrix:
 [[1353  181]
 [ 261 1240]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86      1534
           1       0.87      0.83      0.85      1501

    accuracy                           0.85      3035
   macro avg       0.86      0.85      0.85      3035
weighted avg       0.86      0.85      0.85      3035


--- Austin KNN Classification (minkowski) ---
Accurac

**Austin Housing Dataset:**

This dataset encompasses structured real estate features such as square footage, lot size, and number of bedrooms, alongside sale prices. It is primarily used for regression and classification tasks to predict property values and categorize homes into high- and low-price segments. The data quality allows machine learning models, including K-Nearest Neighbors and ensemble methods, to achieve moderate to high predictive accuracy, with R² scores ranging approximately from 0.45 to 0.85. Feature scaling and selection, as well as choice of distance metrics like Manhattan, significantly impact model performance.



## Airbnb dataset

In [16]:
# Load Airbnb dataset
airbnb_df = pd.read_csv("/Users/sohanaziz/Documents/AI for leaders sem 2/Datasets/cleaned datasets/week 2/listings_cleaned.csv")

# Create binary classification target
median_price = airbnb_df['price'].median()
airbnb_df['high_price'] = (airbnb_df['price'] > median_price).astype(int)

# ----------- Classification -----------
# Drop non-numeric/object columns + missing data
drop_cols = airbnb_df.select_dtypes(include=['object']).columns.tolist() + ['id']
df_class = airbnb_df.drop(columns=drop_cols, errors='ignore').dropna()
df_class = df_class.select_dtypes(include=[np.number])

X = df_class.drop(columns=['high_price'])
y = df_class['high_price']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Run KNN Classification with all distance metrics
for metric in ['euclidean', 'manhattan', 'minkowski']:
    print(f"\n--- Airbnb KNN Classification ({metric}) ---")
    knn_clf = KNeighborsClassifier(n_neighbors=5, metric=metric)
    knn_clf.fit(X_train_cls, y_train_cls)
    y_pred_cls = knn_clf.predict(X_test_cls)
    print("Accuracy:", accuracy_score(y_test_cls, y_pred_cls))
    print("Confusion Matrix:\n", confusion_matrix(y_test_cls, y_pred_cls))
    print("Classification Report:\n", classification_report(y_test_cls, y_pred_cls))

# ----------- Regression -----------
df_reg = airbnb_df.drop(columns=drop_cols + ['high_price'], errors='ignore').dropna()
df_reg = df_reg.select_dtypes(include=[np.number])

X = df_reg.drop(columns=['price'])
y = df_reg['price']

X_scaled = scaler.fit_transform(X)
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Run KNN Regression with all distance metrics
for metric in ['euclidean', 'manhattan', 'minkowski']:
    print(f"\n--- Airbnb KNN Regression ({metric}) ---")
    knn_reg = KNeighborsRegressor(n_neighbors=5, metric=metric)
    knn_reg.fit(X_train_reg, y_train_reg)
    y_pred_reg = knn_reg.predict(X_test_reg)
    rmse = np.sqrt(mean_squared_error(y_test_reg, y_pred_reg))
    r2 = r2_score(y_test_reg, y_pred_reg)
    print(f"RMSE: {rmse:.2f}, R²: {r2:.4f}")


--- Airbnb KNN Classification (euclidean) ---
Accuracy: 0.7989690721649485
Confusion Matrix:
 [[806 189]
 [201 744]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.81      0.81       995
           1       0.80      0.79      0.79       945

    accuracy                           0.80      1940
   macro avg       0.80      0.80      0.80      1940
weighted avg       0.80      0.80      0.80      1940


--- Airbnb KNN Classification (manhattan) ---
Accuracy: 0.8175257731958763
Confusion Matrix:
 [[804 191]
 [163 782]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.81      0.82       995
           1       0.80      0.83      0.82       945

    accuracy                           0.82      1940
   macro avg       0.82      0.82      0.82      1940
weighted avg       0.82      0.82      0.82      1940


--- Airbnb KNN Classification (minkowski) ---
Accuracy: 0.798

**Airbnb Listings Dataset:**

The Airbnb dataset includes a diverse set of features related to rental properties, including host information, availability, and pricing, characterized by greater heterogeneity and sparsity compared to traditional housing data. Regression and classification tasks on this dataset reveal increased complexity, with predictive models achieving moderate classification accuracy (~80%) and regression R² scores up to 0.63. Effective preprocessing, such as removal of non-numeric columns and feature scaling, alongside optimal distance metric selection, notably Manhattan distance, enhance the robustness of KNN and other predictive models applied to this dataset.

